"""empty message

Revision ID: 00de1e2e4d73
Revises: 5fca788121a0
Create Date: 2016-11-24 14:24:10.494958

"""

# revision identifiers, used by Alembic.
revision = '00de1e2e4d73'
down_revision = '5fca788121a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'questionID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'questionID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
