"""empty message

Revision ID: 00f8da978ac1
Revises: 294d687e76cb
Create Date: 2016-10-14 17:02:29.201253

"""

# revision identifiers, used by Alembic.
revision = '00f8da978ac1'
down_revision = '294d687e76cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('personal_id', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('personal_profile', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=32), nullable=True))
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'signature')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signature', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'personal_profile')
    op.drop_column('users', 'personal_id')
    op.drop_column('users', 'permissions')
    ### end Alembic commands ###
