"""empty message

Revision ID: 01f855017cfc
Revises: None
Create Date: 2016-11-26 23:18:52.793717

"""

# revision identifiers, used by Alembic.
revision = '01f855017cfc'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'questionID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'questionID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
