"""empty message

Revision ID: 0a3cb9f1393e
Revises: c59d56daaf40
Create Date: 2016-11-22 21:09:49.494019

"""

# revision identifiers, used by Alembic.
revision = '0a3cb9f1393e'
down_revision = 'c59d56daaf40'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('questionID', sa.Integer(), nullable=True))
    op.add_column('challenges', sa.Column('question_type', sa.Integer(), nullable=False))
    op.drop_column('challenges', 'programID')
    op.drop_column('challenges', 'practiceID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('practiceID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('challenges', sa.Column('programID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('challenges', 'question_type')
    op.drop_column('challenges', 'questionID')
    ### end Alembic commands ###
