"""empty message

Revision ID: 0ddf19535a25
Revises: de5f82a0a6bb
Create Date: 2016-11-08 10:54:42.960376

"""

# revision identifiers, used by Alembic.
revision = '0ddf19535a25'
down_revision = 'de5f82a0a6bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'createdTime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('topics', 'createdTime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('topics', 'updatedTime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'updatedTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('topics', 'createdTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('post', 'createdTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###
