"""empty message

Revision ID: 1d204e7ba433
Revises: 9c02b543228e
Create Date: 2016-11-06 19:13:06.425903

"""

# revision identifiers, used by Alembic.
revision = '1d204e7ba433'
down_revision = '9c02b543228e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submit_problem', 'code',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('submit_problem', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('submit_problem', 'submit_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(u'submit_problem_ibfk_1', 'submit_problem', type_='foreignkey')
    op.drop_constraint(u'submit_problem_ibfk_2', 'submit_problem', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'submit_problem_ibfk_2', 'submit_problem', 'users', ['uid'], ['id'])
    op.create_foreign_key(u'submit_problem_ibfk_1', 'submit_problem', 'programs', ['pid'], ['id'])
    op.alter_column('submit_problem', 'submit_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('submit_problem', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('submit_problem', 'code',
               existing_type=mysql.TEXT(),
               nullable=False)
    ### end Alembic commands ###
