"""empty message

Revision ID: 25847cdd86ba
Revises: 4f8631ac7016
Create Date: 2016-10-16 10:17:43.155659

"""

# revision identifiers, used by Alembic.
revision = '25847cdd86ba'
down_revision = '4f8631ac7016'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('postNum', sa.Integer(), nullable=False))
    op.drop_column('users', 'postsNum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('postsNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('users', 'postNum')
    ### end Alembic commands ###
