"""empty message

Revision ID: 294d687e76cb
Revises: e8a996052c78
Create Date: 2016-10-12 18:09:33.252849

"""

# revision identifiers, used by Alembic.
revision = '294d687e76cb'
down_revision = 'e8a996052c78'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice_classifies',
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('classify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['classify_id'], ['classifies.id'], )
    )
    op.drop_column(u'choices', 'classify')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'choices', sa.Column('classify', mysql.VARCHAR(length=64), nullable=False))
    op.drop_table('choice_classifies')
    op.drop_table('classifies')
    ### end Alembic commands ###
