"""empty message

Revision ID: 3579089a3187
Revises: None
Create Date: 2016-12-04 16:23:05.684159

"""

# revision identifiers, used by Alembic.
revision = '3579089a3187'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_code_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('uri', sa.String(length=256), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['case_codes.version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'case_codes_ibfk_1', 'case_codes', type_='foreignkey')
    op.create_foreign_key(None, 'case_codes', 'cases', ['case_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_codes', type_='foreignkey')
    op.create_foreign_key(u'case_codes_ibfk_1', 'case_codes', 'cases', ['case_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_table('case_code_materials')
    ### end Alembic commands ###
