"""empty message

Revision ID: 3f766510a095
Revises: a11102927c9e
Create Date: 2016-10-11 19:12:25.021106

"""

# revision identifiers, used by Alembic.
revision = '3f766510a095'
down_revision = 'a11102927c9e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_activity')
    op.drop_table('rates')
    op.drop_column('courses', 'voteNum')
    op.add_column('materials', sa.Column('lessonId', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('m_type', sa.String(length=64), nullable=False))
    op.drop_constraint(u'materials_ibfk_1', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'lessons', ['lessonId'], ['id'])
    op.drop_column('materials', 'courseId')
    op.drop_column('materials', 'size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('courseId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(u'materials_ibfk_1', 'materials', 'courses', ['courseId'], ['id'])
    op.drop_column('materials', 'm_type')
    op.drop_column('materials', 'lessonId')
    op.add_column('courses', sa.Column('voteNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('rates',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('createdTime', mysql.DATETIME(), nullable=True),
    sa.Column('courseId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courseId'], [u'courses.id'], name=u'rates_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_activity',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('students')
    ### end Alembic commands ###
