"""empty message

Revision ID: 4769d6d4b8dd
Revises: 4a11bbc11e31
Create Date: 2017-04-11 08:57:23.996000

"""

# revision identifiers, used by Alembic.
revision = '4769d6d4b8dd'
down_revision = '4a11bbc11e31'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vnc_progresses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vnc_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('have_done', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vnc_knowledge_id'], ['vnc_knowledge.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vnc_knowledge_id')
    )
    op.create_table('vnc_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vnc_knowledge_id', sa.Integer(), nullable=True),
    sa.Column('vnc_task_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vnc_knowledge_id'], ['vnc_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lab_programs')
    op.alter_column(u'apply', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column(u'apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column(u'challenges', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column(u'challenges', 'title',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column(u'courses', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'courses', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_constraint(u'homework_ibfk_1', 'homework', type_='foreignkey')
    op.create_foreign_key(None, 'homework', 'courses', ['course_id'], ['id'])
    op.drop_constraint(u'homework_appendix_ibfk_1', 'homework_appendix', type_='foreignkey')
    op.drop_constraint(u'homework_appendix_ibfk_2', 'homework_appendix', type_='foreignkey')
    op.create_foreign_key(None, 'homework_appendix', 'homework', ['homework_id'], ['id'])
    op.create_foreign_key(None, 'homework_appendix', 'users', ['user_id'], ['id'])
    op.drop_constraint(u'homework_upload_ibfk_2', 'homework_upload', type_='foreignkey')
    op.drop_constraint(u'homework_upload_ibfk_1', 'homework_upload', type_='foreignkey')
    op.create_foreign_key(None, 'homework_upload', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'homework_upload', 'homework', ['homework_id'], ['id'])
    op.alter_column(u'lessons', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'lessons', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.add_column(u'programs', sa.Column('default_code', sa.Text(), nullable=True))
    op.alter_column(u'programs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'qrcode', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column(u'questions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('course_id', table_name='questions')
    op.alter_column(u'submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(u'user_questions_ibfk_1', 'user_questions', type_='foreignkey')
    op.alter_column(u'users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'users', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(u'user_questions_ibfk_1', 'user_questions', 'users', ['user_id'], ['id'])
    op.alter_column(u'submit_problem', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('course_id', 'questions', ['user_id'], unique=False)
    op.alter_column(u'questions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'qrcode', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'programs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column(u'programs', 'default_code')
    op.alter_column(u'lessons', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column(u'lessons', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'homework_upload', type_='foreignkey')
    op.drop_constraint(None, 'homework_upload', type_='foreignkey')
    op.create_foreign_key(u'homework_upload_ibfk_1', 'homework_upload', 'homework', ['homework_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'homework_upload_ibfk_2', 'homework_upload', 'users', ['user_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'homework_appendix', type_='foreignkey')
    op.drop_constraint(None, 'homework_appendix', type_='foreignkey')
    op.create_foreign_key(u'homework_appendix_ibfk_2', 'homework_appendix', 'users', ['user_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'homework_appendix_ibfk_1', 'homework_appendix', 'homework', ['homework_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'homework', type_='foreignkey')
    op.create_foreign_key(u'homework_ibfk_1', 'homework', 'courses', ['course_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.alter_column(u'courses', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column(u'courses', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'challenges', 'title',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column(u'challenges', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column(u'apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column(u'apply', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.create_table('lab_programs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('source_code', mysql.TEXT(), nullable=False),
    sa.Column('default_code', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('vnc_tasks')
    op.drop_table('vnc_progresses')
    ### end Alembic commands ###
