"""empty message

Revision ID: 4a11bbc11e31
Revises: None
Create Date: 2017-04-10 20:58:18.985000

"""

# revision identifiers, used by Alembic.
revision = '4a11bbc11e31'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visitNum', sa.Integer(), nullable=True),
    sa.Column('updatedTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('memberNum', sa.Integer(), nullable=True),
    sa.Column('topicNum', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=False),
    sa.Column('university', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('is_password_reset_link_valid', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.Column('personal_profile', sa.Text(), nullable=True),
    sa.Column('topicNum', sa.Integer(), nullable=False),
    sa.Column('postNum', sa.Integer(), nullable=False),
    sa.Column('commentNum', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('case_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('dir_path', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=128), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('beginTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('lessonNum', sa.Integer(), nullable=False),
    sa.Column('studentNum', sa.Integer(), nullable=True),
    sa.Column('smallPicture', sa.String(length=128), nullable=True),
    sa.Column('middlePicture', sa.String(length=128), nullable=True),
    sa.Column('largePicture', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('nature_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('knowledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('acceptedNum', sa.Integer(), nullable=True),
    sa.Column('submitNum', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.Column('solution', sa.String(length=512), nullable=False),
    sa.Column('analysis', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visitNum', sa.Integer(), nullable=True),
    sa.Column('postNum', sa.Integer(), nullable=True),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('updatedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_questions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=128), nullable=False),
    sa.Column('last_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['classifies.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'classify_id', 'question_type')
    )
    op.create_table('vnc_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_code_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('uri', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['case_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('courseId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('courseId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('about', sa.String(length=128), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('topicID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topicID'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('cur_progress', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'knowledge_id')
    )
    op.create_table('qrcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_classifies',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['classifies.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'classify_id')
    )
    op.create_table('submit_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnc_progresses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vnc_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('have_done', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vnc_knowledge_id'], ['vnc_knowledge.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vnc_knowledge_id')
    )
    op.create_table('vnc_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vnc_knowledge_id', sa.Integer(), nullable=True),
    sa.Column('vnc_task_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vnc_knowledge_id'], ['vnc_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_appendix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=256), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=256), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=True),
    sa.Column('m_type', sa.String(length=128), nullable=False),
    sa.Column('lessonId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lessonId'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'paper_id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('knowledgeId', sa.Integer(), nullable=True),
    sa.Column('knowledgeNum', sa.Integer(), nullable=True),
    sa.Column('materialId', sa.Integer(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('default_code', sa.Text(), nullable=True),
    sa.Column('task_number', sa.Integer(), nullable=True),
    sa.Column('cpu_number_per_task', sa.Integer(), nullable=True),
    sa.Column('node_number', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['knowledgeId'], ['knowledges.id'], ),
    sa.ForeignKeyConstraint(['materialId'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    op.drop_table('paper_question')
    op.drop_table('materials')
    op.drop_table('homework_upload')
    op.drop_table('homework_appendix')
    op.drop_table('vnc_tasks')
    op.drop_table('vnc_progresses')
    op.drop_table('submit_problem')
    op.drop_table('question_classifies')
    op.drop_table('qrcode')
    op.drop_table('progress')
    op.drop_table('post')
    op.drop_table('papers')
    op.drop_table('lessons')
    op.drop_table('homework')
    op.drop_table('course_users')
    op.drop_table('comments')
    op.drop_table('case_code_materials')
    op.drop_table('apply')
    op.drop_table('vnc_knowledge')
    op.drop_table('user_questions')
    op.drop_table('topics')
    op.drop_table('questions')
    op.drop_table('programs')
    op.drop_table('knowledges')
    op.drop_table('group_members')
    op.drop_table('courses')
    op.drop_table('case_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('code_cache')
    op.drop_table('classifies')
    op.drop_table('cases')
    op.drop_table('articles')
    ### end Alembic commands ###
