"""empty message

Revision ID: 52dbc735b9b7
Revises: 25847cdd86ba
Create Date: 2016-10-16 11:09:29.328301

"""

# revision identifiers, used by Alembic.
revision = '52dbc735b9b7'
down_revision = '25847cdd86ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'group_members_ibfk_1', 'group_members', type_='foreignkey')
    op.drop_constraint(u'group_members_ibfk_2', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(u'group_members_ibfk_2', 'group_members', 'groups', ['user_id'], ['id'])
    op.create_foreign_key(u'group_members_ibfk_1', 'group_members', 'users', ['group_id'], ['id'])
    ### end Alembic commands ###
