"""empty message

Revision ID: 5fca788121a0
Revises: 0a3cb9f1393e
Create Date: 2016-11-24 13:35:13.070685

"""

# revision identifiers, used by Alembic.
revision = '5fca788121a0'
down_revision = '0a3cb9f1393e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('cur_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'knowledge_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    ### end Alembic commands ###
