"""empty message

Revision ID: 7340064eed8c
Revises: d3dc8710e16b
Create Date: 2016-09-20 09:48:41.709086

"""

# revision identifiers, used by Alembic.
revision = '7340064eed8c'
down_revision = 'd3dc8710e16b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('largePicture', sa.String(length=64), nullable=True))
    op.add_column('courses', sa.Column('middlePicture', sa.String(length=64), nullable=True))
    op.add_column('courses', sa.Column('smallPicture', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'smallPicture')
    op.drop_column('courses', 'middlePicture')
    op.drop_column('courses', 'largePicture')
    ### end Alembic commands ###
