"""empty message

Revision ID: 8be18de84c21
Revises: 9c53f6450843
Create Date: 2016-10-12 10:35:36.786655

"""

# revision identifiers, used by Alembic.
revision = '8be18de84c21'
down_revision = '9c53f6450843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'course_users_ibfk_1', 'course_users', type_='foreignkey')
    op.drop_constraint(u'course_users_ibfk_2', 'course_users', type_='foreignkey')
    op.create_foreign_key(None, 'course_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'course_users', 'courses', ['course_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_users', type_='foreignkey')
    op.drop_constraint(None, 'course_users', type_='foreignkey')
    op.create_foreign_key(u'course_users_ibfk_2', 'course_users', 'courses', ['user_id'], ['id'])
    op.create_foreign_key(u'course_users_ibfk_1', 'course_users', 'users', ['course_id'], ['id'])
    ### end Alembic commands ###
