"""empty message

Revision ID: a11102927c9e
Revises: 95f2d4367f60
Create Date: 2016-09-29 14:28:22.049044

"""

# revision identifiers, used by Alembic.
revision = 'a11102927c9e'
down_revision = '95f2d4367f60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('acceptedNum', sa.Integer(), nullable=True),
    sa.Column('submitNum', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    ### end Alembic commands ###
