"""empty message

Revision ID: a3466a9c9a78
Revises: None
Create Date: 2016-12-02 10:13:35.833934

"""

# revision identifiers, used by Alembic.
revision = 'a3466a9c9a78'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'case_codes_ibfk_1', 'case_codes', type_='foreignkey')
    op.create_foreign_key(None, 'case_codes', 'cases', ['case_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_codes', type_='foreignkey')
    op.create_foreign_key(u'case_codes_ibfk_1', 'case_codes', 'cases', ['case_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    ### end Alembic commands ###
