"""empty message

Revision ID: b222e17012cd
Revises: f215904daceb
Create Date: 2016-12-06 15:07:59.195040

"""

# revision identifiers, used by Alembic.
revision = 'b222e17012cd'
down_revision = 'f215904daceb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('dir_path', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_code_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('uri', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['case_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_codes')
    op.add_column(u'cases', sa.Column('icon', sa.String(length=64), nullable=True))
    op.alter_column(u'users', 'is_password_reset_link_valid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'users', 'is_password_reset_link_valid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column(u'cases', 'icon')
    op.create_table('case_codes',
    sa.Column('case_id', mysql.INTEGER(display_width=64), autoincrement=False, nullable=False),
    sa.Column('version_id', mysql.INTEGER(display_width=64), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=256), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=256), nullable=False),
    sa.Column('code_path', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], [u'cases.id'], name=u'case_codes_ibfk_1'),
    sa.PrimaryKeyConstraint('case_id', 'version_id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('case_code_materials')
    op.drop_table('case_versions')
    ### end Alembic commands ###
