"""empty message

Revision ID: b22adb3fca17
Revises: None
Create Date: 2016-12-30 17:17:27.257005

"""

# revision identifiers, used by Alembic.
revision = 'b22adb3fca17'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apply', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.drop_constraint(u'case_code_materials_ibfk_1', 'case_code_materials', type_='foreignkey')
    op.create_foreign_key(None, 'case_code_materials', 'case_versions', ['version_id'], ['id'])
    op.alter_column('cases', 'icon',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               nullable=False)
    op.alter_column('courses', 'public',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text(u"'1'"))
    op.drop_constraint(u'homework_ibfk_1', 'homework', type_='foreignkey')
    op.create_foreign_key(None, 'homework', 'courses', ['course_id'], ['id'])
    op.drop_constraint(u'homework_upload_ibfk_2', 'homework_upload', type_='foreignkey')
    op.drop_constraint(u'homework_upload_ibfk_1', 'homework_upload', type_='foreignkey')
    op.create_foreign_key(None, 'homework_upload', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'homework_upload', 'homework', ['homework_id'], ['id'])
    op.alter_column('qrcode', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('qrcode', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'homework_upload', type_='foreignkey')
    op.drop_constraint(None, 'homework_upload', type_='foreignkey')
    op.create_foreign_key(u'homework_upload_ibfk_1', 'homework_upload', 'homework', ['homework_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'homework_upload_ibfk_2', 'homework_upload', 'users', ['user_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'homework', type_='foreignkey')
    op.create_foreign_key(u'homework_ibfk_1', 'homework', 'courses', ['course_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.alter_column('courses', 'public',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text(u"'1'"))
    op.alter_column('cases', 'icon',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               nullable=True)
    op.drop_constraint(None, 'case_code_materials', type_='foreignkey')
    op.create_foreign_key(u'case_code_materials_ibfk_1', 'case_code_materials', 'case_versions', ['version_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.alter_column('apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('apply', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    ### end Alembic commands ###
