"""empty message

Revision ID: c59d56daaf40
Revises: f536d956b308
Create Date: 2016-11-22 16:31:23.187318

"""

# revision identifiers, used by Alembic.
revision = 'c59d56daaf40'
down_revision = 'f536d956b308'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('knowledgeNum', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'knowledgeNum')
    ### end Alembic commands ###
