"""empty message

Revision ID: e31ec808590a
Revises: b222e17012cd
Create Date: 2016-12-06 15:11:08.963507

"""

# revision identifiers, used by Alembic.
revision = 'e31ec808590a'
down_revision = 'b222e17012cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'icon',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               nullable=False)
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('cases', 'icon',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               nullable=True)
    ### end Alembic commands ###
