"""empty message

Revision ID: e8a996052c78
Revises: 05794eba026c
Create Date: 2016-10-12 17:24:04.160804

"""

# revision identifiers, used by Alembic.
revision = 'e8a996052c78'
down_revision = '05794eba026c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('classify', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choices', 'classify')
    ### end Alembic commands ###
