"""empty message

Revision ID: f215904daceb
Revises: None
Create Date: 2016-12-05 08:45:23.310594

"""

# revision identifiers, used by Alembic.
revision = 'f215904daceb'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('case_codes', 'code_path',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_constraint(u'case_codes_ibfk_1', 'case_codes', type_='foreignkey')
    op.create_foreign_key(None, 'case_codes', 'cases', ['case_id'], ['id'])
    op.alter_column('classifies', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('courses', 'largePicture',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('courses', 'middlePicture',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('courses', 'smallPicture',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('courses', 'subtitle',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('courses', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('groups', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('lessons', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('materials', 'm_type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('materials', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('materials', 'uri',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('programs', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('submit_problem', 'language',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('submit_problem', 'status',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('topics', 'title',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'personal_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'telephone',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'website',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'website',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('users', 'telephone',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'personal_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'is_password_reset_link_valid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('topics', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('submit_problem', 'status',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('submit_problem', 'language',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('programs', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('materials', 'uri',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('materials', 'name',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('materials', 'm_type',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('lessons', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('groups', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('courses', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('courses', 'subtitle',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('courses', 'smallPicture',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('courses', 'middlePicture',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('courses', 'largePicture',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('classifies', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'case_codes', type_='foreignkey')
    op.create_foreign_key(u'case_codes_ibfk_1', 'case_codes', 'cases', ['case_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.alter_column('case_codes', 'code_path',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=64),
               existing_nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    ### end Alembic commands ###
