"""empty message

Revision ID: f536d956b308
Revises: a68bf50b0489
Create Date: 2016-11-22 16:18:08.890707

"""

# revision identifiers, used by Alembic.
revision = 'f536d956b308'
down_revision = 'a68bf50b0489'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('knowledgeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'challenges', 'knowledges', ['knowledgeId'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'knowledgeId')
    ### end Alembic commands ###
